# Generated by Django 4.0.1 on 2022-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='licence_expiry_date',
            field=models.DateField(max_length=10),
        ),
    ]
