# Generated by Django 4.0.1 on 2022-05-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_driver_licence_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='experience',
            field=models.CharField(max_length=2),
        ),
    ]
