# Generated by Django 4.0.1 on 2022-05-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_driver_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_assigned',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicle'),
        ),
    ]
