# Generated by Django 4.0.1 on 2022-05-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_driver_vehicle_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='licence_expiry_date',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_assigned',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.vehicle'),
        ),
    ]
