# Generated by Django 4.0.1 on 2022-05-29 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.vehicle'),
        ),
    ]
